baseurl: /lisbon
permalink: pretty
markdown: kramdown
paginate: 5
repo: lisbon
github_org: maptime
maptime:
  chapter: MaptimeLisbon
  twitter: TwitterHandle
  #disqus: YOUR DISQUS USERNAME

gems:
  - jekyll-feed
